=== apple-x-co/go-pdf/json_schema/document.json
{
  "$id": "document.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "go-pdf document validation",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "width": {
      "type": "integer"
    },
    "height": {
      "type": "integer"
    },
    "text_size": {
      "type": "integer"
    },
    "compress_level": {
      "type": "integer"
    },
    "inset": {
      "type": "object",
      "$ref": "definitions.json#/definitions/inset"
    },
    "password": {
      "type": "string"
    },
    "templates": {
      "type": "array",
      "items": {
        "$ref": "definitions.json#/definitions/element_template"
      }
    },
    "header": {
      "$ref": "definitions.json#/definitions/header"
    },
    "footer": {
      "$ref": "definitions.json#/definitions/footer"
    },
    "pages": {
      "type": "array",
      "items": {
        "$ref": "definitions.json#/definitions/page"
      }
    }
  },
  "additionalProperties": false
}

=== apple-x-co/go-pdf/samples/commpress-level/layout.json
{
  "$schema": "../../json_schema/document.json",
  "width": 595,
  "height": 842,
  "compress_level": 9,
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "image",
            "attributes": {
              "path": "work/sample1.jpg"
            }
          }
        ]
      }
    }
  ]
}

=== apple-x-co/go-pdf/samples/header-footer/layout.json
{
  "$schema": "../../json_schema/document.json",
  "width": 595,
  "height": 842,
  "header": {
    "size": {
      "width": 595,
      "height": 20
    },
    "liner_layout": {
      "orientation": "horizontal",
      "elements": [
        {
          "type": "text",
          "attributes": {
            "text": "HEADER",
            "size": {
              "width": 575,
              "height": 20
            },
            "border": {
              "width": 1,
              "color": {
                "r": 175,
                "g": 223,
                "b": 228
              }
            }
          }
        }
      ]
    }
  },
  "footer": {
    "size": {
      "width": 595,
      "height": 20
    },
    "liner_layout": {
      "orientation": "horizontal",
      "elements": [
        {
          "type": "text",
          "attributes": {
            "text": "FOOTER",
            "size": {
              "width": 575,
              "height": 20
            },
            "border": {
              "width": 1,
              "color": {
                "r": 175,
                "g": 223,
                "b": 228
              }
            }
          }
        }
      ]
    }
  },
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "attributes": {
              "text": "PAGE1"
            }
          }
        ]
      }
    },
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "attributes": {
              "text": "PAGE2"
            }
          }
        ]
      }
    }
  ]
}

=== apple-x-co/go-pdf/samples/image-template/layout.json
{
  "$schema": "../../json_schema/document.json",
  "width": 595,
  "height": 842,
  "templates": [
    {
      "type": "image",
      "id": "template-t1",
      "attributes": {
        "size": {
          "width": 100
        }
      }
    }
  ],
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "image",
            "template_id": "template-t1",
            "attributes": {
              "path": "work/sample1.jpg"
            }
          },
          {
            "type": "image",
            "template_id": "template-t1",
            "attributes": {
              "path": "work/sample2.jpg"
            }
          }
        ]
      }
    }
  ]
}

=== apple-x-co/go-pdf/samples/page-header-footer/layout.json
{
  "width": 595,
  "height": 842,
  "header": {
    "size": {
      "width": 595,
      "height": 20
    },
    "liner_layout": {
      "orientation": "horizontal",
      "elements": [
        {
          "type": "text",
          "attributes": {
            "text": "GLOBAL HEADER",
            "size": {
              "width": 575,
              "height": 20
            },
            "border": {
              "width": 1,
              "color": {
                "r": 59,
                "g": 175,
                "b": 117
              }
            }
          }
        }
      ]
    }
  },
  "footer": {
    "size": {
      "width": 595,
      "height": 20
    },
    "liner_layout": {
      "orientation": "horizontal",
      "elements": [
        {
          "type": "text",
          "attributes": {
            "text": "GLOBAL FOOTER",
            "size": {
              "width": 575,
              "height": 20
            },
            "border": {
              "width": 1,
              "color": {
                "r": 59,
                "g": 175,
                "b": 117
              }
            }
          }
        }
      ]
    }
  },
  "pages": [
    {
      "page_header": {
        "size": {
          "width": 575,
          "height": 20
        },
        "liner_layout": {
          "orientation": "horizontal",
          "elements": [
            {
              "type": "text",
              "attributes": {
                "text": "PAGE HEADER",
                "size": {
                  "width": 575,
                  "height": 20
                },
                "border": {
                  "width": 1,
                  "color": {
                    "r": 175,
                    "g": 223,
                    "b": 228
                  }
                }
              }
            }
          ]
        }
      },
      "page_footer": {
        "size": {
          "width": 575,
          "height": 20
        },
        "liner_layout": {
          "orientation": "horizontal",
          "elements": [
            {
              "type": "text",
              "attributes": {
                "text": "PAGE FOOTER",
                "size": {
                  "width": 575,
                  "height": 20
                },
                "border": {
                  "width": 1,
                  "color": {
                    "r": 175,
                    "g": 223,
                    "b": 228
                  }
                }
              }
            }
          ]
        }
      },
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "attributes": {
              "text": "PAGE1"
            }
          }
        ]
      }
    },
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "attributes": {
              "text": "PAGE2"
            }
          }
        ]
      }
    }
  ]
}

=== apple-x-co/go-pdf/samples/text-content-margin/layout.json
{
  "$schema": "../../json_schema/document.json",
  "width": 595,
  "height": 842,
  "text_size": 8,
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "attributes": {
              "text": "NO CONTENT MARGIN",
              "border": {
                "width": 1,
                "color": {
                  "r": 175,
                  "g": 223,
                  "b": 228
                }
              }
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "CONTENT MARGIN - LEFT",
              "content_margin": {
                "left": 5
              },
              "border": {
                "width": 1,
                "color": {
                  "r": 175,
                  "g": 223,
                  "b": 228
                }
              }
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "CONTENT MARGIN - TOP",
              "content_margin": {
                "top": 5
              },
              "border": {
                "width": 1,
                "color": {
                  "r": 175,
                  "g": 223,
                  "b": 228
                }
              }
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "CONTENT MARGIN - RIGHT",
              "content_margin": {
                "right": 5
              },
              "border": {
                "width": 1,
                "color": {
                  "r": 175,
                  "g": 223,
                  "b": 228
                }
              }
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "CONTENT MARGIN - BOTTOM",
              "content_margin": {
                "bottom": 5
              },
              "border": {
                "width": 1,
                "color": {
                  "r": 175,
                  "g": 223,
                  "b": 228
                }
              }
            }
          }
        ]
      }
    }
  ]
}

=== apple-x-co/go-pdf/samples/password-protect/layout.json
{
  "width": 595,
  "height": 842,
  "password": "passw0rd",
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "attributes": {
              "text": "PROTECTED"
            }
          }
        ]
      }
    }
  ]
}

=== apple-x-co/go-pdf/samples/text-template/layout.json
{
  "$schema": "../../json_schema/document.json",
  "width": 595,
  "height": 842,
  "templates": [
    {
      "type": "text",
      "id": "template-t1",
      "attributes": {
        "color": {
          "r": 175,
          "g": 223,
          "b": 228
        }
      }
    }
  ],
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "template_id": "template-t1",
            "attributes": {
              "text": "style by template"
            }
          }
        ]
      }
    }
  ]
}

=== apple-x-co/go-pdf/samples/text-linebreak/layout.json
{
  "$schema": "../../json_schema/document.json",
  "width": 595,
  "height": 842,
  "text_size": 18,
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
          {
            "type": "text",
            "attributes": {
              "text": "TEXT1"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT2"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT3"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT4"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT5"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT6"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT7"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT8"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT9"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT10"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT11"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT12"
            }
          },
          {
            "type": "text",
            "attributes": {
              "text": "TEXT13"
            }
          }
        ]
      }
    },
    {
      "liner_layout": {
        "orientation": "horizontal",
        "liner_layouts": [
          {
            "orientation": "horizontal",
            "elements": [
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT1"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT2"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT3"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT4"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT5"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT6"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT7"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT8"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT9"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT10"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT11"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT12"
                }
              },
              {
                "type": "text",
                "attributes": {
                  "text": "TEXT13"
                }
              }
            ]
          }
        ]
      }
    }
  ]
}
