=== apple-x-co/go-pdf/json_schema/document.json
{
  "$id": "document.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "go-pdf document validation",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "width": {
      "type": "integer"
    },
    "height": {
      "type": "integer"
    },
    "text_size": {
      "type": "integer"
    },
    "compress_level": {
      "type": "integer"
    },
    "inset": {
      "type": "object",
      "$ref": "definitions.json#/definitions/inset"
    },
    "password": {
      "type": "string"
    },
    "templates": {
      "type": "array",
      "items": {
        "$ref": "definitions.json#/definitions/element_template"
      }
    },
    "header": {
      "$ref": "definitions.json#/definitions/header"
    },
    "footer": {
      "$ref": "definitions.json#/definitions/footer"
    },
    "pages": {
      "type": "array",
      "items": {
        "$ref": "definitions.json#/definitions/page"
      }
    }
  },
  "additionalProperties": false
}

=== apple-x-co/go-pdf/samples/sample-report/layout.json
{
  "width": 842,
  "height": 595,
  "header": {
    "size": {
      "width": 822,
      "height": 20
    },
    "liner_layout": {
      "orientation": "horizontal",
      "layout": {
        "width": "match_parent",
        "height": "match_parent",
        "weight": 1
      },
      "elements": [
        {
          "type": "text",
          "attributes": {
            "text": "Sales Report",
            "text_size": 16,
            "layout": {
              "width": "match_parent",
              "weight": 0.9
            },
            "align": "center",
            "valign": "middle"
          }
        },
        {
          "type": "text",
          "attributes": {
            "text": "page 1",
            "text_size": 10,
            "layout": {
              "width": "match_parent",
              "weight": 0.1
            },
            "align": "right",
            "valign": "middle"
          }
        }
      ]
    }
  },
  "footer": {
    "size": {
      "width": 822,
      "height": 20
    },
    "liner_layout": {
      "orientation": "horizontal",
      "layout": {
        "width": "match_parent",
        "height": "match_parent",
        "weight": 1
      },
      "elements": [
        {
          "type": "text",
          "attributes": {
            "text": "Created 2019-04-26",
            "text_size": 10,
            "layout": {
              "width": "match_parent",
              "height": "match_parent",
              "weight": 1
            },
            "align": "right",
            "valign": "bottom"
          }
        }
      ]
    }
  },
  "pages": [
    {
      "liner_layout": {
        "orientation": "horizontal",
        "elements": [
        ]
      }
    }
  ]
}
